name: CI

on: [push, pull_request]

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --diff --dry-run

  phpstan:
    name: 'PHPStan'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Composer
        uses: php-actions/composer@v5
        with:
          php_version: 8.0
      - name: PHPStan
        uses: php-actions/phpstan@v2
        with:
          php_version: 8.0

  phpunit:
    name: 'PHPUnit'
    runs-on: ${{ matrix.ubuntu-version }}
    strategy:
      # Making sure all versions get tested even if one fails
      fail-fast: false
      matrix:
        include:
          # 7.2 needs older phpunit version and older ubuntu
          - php-version: '7.2'
            phpunit-version: '8.5.13'
            ubuntu-version: 'ubuntu-18.04'
          # 7.3 is no longer supported in newer ubuntu
          - php-version: '7.3'
            phpunit-version: '9.5.0'
            ubuntu-version: 'ubuntu-18.04'
          # 7.4 and 8.0 are supported in both old and new ubuntu, going with newer one only here
          - php-version: '7.4'
            phpunit-version: '9.5.0'
            ubuntu-version: 'ubuntu-20.04'
          - php-version: '8.0'
            phpunit-version: '9.5.0'
            ubuntu-version: 'ubuntu-20.04'
    steps:
      - uses: actions/checkout@v2
      - name: Composer
        uses: php-actions/composer@v5
        with:
          php_version: ${{ matrix.php-version }}

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        with:
          version: ${{ matrix.phpunit-version }}
          php_version: ${{ matrix.php-version }}
          #args: --coverage-text
