name: CI

on: [push, pull_request]

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
      - name: Install dependencies
        uses: ramsey/composer-install@v3
      - name: PHP-CS-Fixer
        run: vendor/bin/php-cs-fixer fix --diff --dry-run

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
      - name: Install dependencies
        uses: ramsey/composer-install@v3
      - name: PHPStan
        run: vendor/bin/phpstan analyse --no-progress

  phpunit:
    name: 'PHPUnit (PHP ${{ matrix.php-version }})'
    runs-on: ubuntu-latest
    strategy:
      # Making sure all versions get tested even if one fails
      fail-fast: false
      matrix:
        php-version: ['8.1', '8.2', '8.3', '8.4']
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
      - name: Install dependencies
        uses: ramsey/composer-install@v3
      - name: PHPUnit Tests
        run: vendor/bin/phpunit
