name: CI

on: [push]

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --diff --dry-run

  phpstan:
    name: 'PHPStan'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Composer
        uses: php-actions/composer@v5
        with:
          php_version: 8.0
          composer_version: 2
      - name: PHPStan
        uses: php-actions/phpstan@v2
        with:
          php_version: 8.0

  phpunit:
    name: 'PHPUnit'
    runs-on: ubuntu-latest
    strategy:
      # Making sure all versions get tested even if one fails
      fail-fast: false
      matrix:
        phpunit-version:
          - '9.5.0'
        php-version:
          - '7.3'
          - '7.4'
          - '8.0'
        include:
          - phpunit-version: '8.5.13'
            php-version: '7.2'

    steps:
      - uses: actions/checkout@v2
      - name: Composer
        uses: php-actions/composer@v5
        with:
          php_version: ${{ matrix.php-version }}

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        with:
          version: ${{ matrix.phpunit-version }}
          php_version: ${{ matrix.php-version }}
          #bootstrap: vendor/autoload.php
          #configuration: test/phpunit.xml
          #args: --coverage-text
